# Generated by Django 5.0.6 on 2024-06-27 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('gasolina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
